Metadata docs
QutEcoacoustics/emu pull request #211
Opened 2022-07-07 15:03 UTC by noahmacaskill

Some general corrections and improvements.

The SD card capacity I've extracted is in KiB, could convert to GB (or GiB), looking at the Reclog file it is in GiB. Changed bits per sample to bits per second (bits per sample as I understand it is bit depth, which is already there, bits per second was missing). Also removed byte rate and block align since they aren't part of our final metadata output.

A couple other small improvements.

2022-07-08 00:16 UTC, atruskie commented
Nice. 

I'd prefer to normalize both of those memory card values to bytes and bytes per second if possible - better than changing the docs to be inconsistent.

2022-07-14 01:06 UTC, atruskie requested changes

2022-07-14 01:06 UTC, atruskie commented on src/Emu/Metadata/FrontierLabs/LogFileExtractor.cs
> +        public const int KilobyteConversion = 1024;
These are incorrect?. Normally these are the correct values to use, but the units you're converting are already measured as <x>bytes.  e.g. these would be correct converting from decimal units to bytes.

I double checked, so I think I'm correct here... the numbers in Fixtures.yaml don't make sense

![image](https://user-images.githubusercontent.com/1452968/178862271-284ef130-2ff5-44ff-97ec-77649d58cc85.png)

Whereas, simply scaling magnitudes:

![image](https://user-images.githubusercontent.com/1452968/178862349-5434d1cd-adc5-4afd-b699-1cf9d0f47716.png)

![image](https://user-images.githubusercontent.com/1452968/178862211-5a11ebbf-c4fe-40c4-8ce2-016f342947db.png)

2022-07-14 01:06 UTC, atruskie commented on src/Emu/Metadata/FrontierLabs/LogFileExtractor.cs
> +        public const int KilobyteConversion = 1024;
It should be noted that SD uses MB/s (the base 10 scale) everywhere as opposed to MiB/s (the base 2 scale): https://www.sdcard.org/developers/sd-standard-overview/bus-speed-default-speed-high-speed-uhs-sd-express/

I'm fairly sure I'm correct....

2022-07-21 17:00 UTC, noahmacaskill commented
Sorry it took so long on this, had my hands tied on some other work. I'm realizing the capacity values were so far off because of overflow, need a long to store that # of bytes. Aside from that, I think you're right, the capacity and speed values are in base 10.

2022-07-22 06:26 UTC, merged