Created no checksum option
QutEcoacoustics/emu pull request #241
Opened 2022-08-22 21:05 UTC by noahmacaskill

Had a go at creating the no-checksum option. Injected the option into the hash calculator itself, realizing the testing infrastructure isn't set up for that to work (makes sense). Thinking of where it would be best to inject the option, maybe in [Metadata.cs](https://github.com/QutEcoacoustics/emu/blob/master/src/Emu/Commands/Metadata/Metadata.cs)? Let me know your thoughts.

Closes #228

2022-08-23 07:05 UTC, atruskie requested changes
Okay, yeah, I agree a better spot for this would be in Metadata.cs, just inside InvokeAsync:

https://github.com/QutEcoacoustics/emu/blob/1127551ad5325809f15f8f915c7abdd2b99658db/src/Emu/Commands/Metadata/Metadata.cs#L49

If this.NoChecksum is true, then filter out any type of `HashCalculator` from the register.All list.

The associated unit test is quite simple then too: create a new metadata command, set nochecksum to true/false and verify presence of typeof(HashCalculator) in this.AllExtractors.

2022-08-23 07:05 UTC, atruskie commented on src/Emu/Metadata/HashCalculator.cs
> +        public HashCalculator(FileUtilities fileUtilities, EmuGlobalOptions options)
I agree and don't think this is a good spot for this injection.

2022-08-23 07:05 UTC, atruskie commented on test/Emu.Tests/Metadata/HashCalculatorTests.cs
> +        }
revert - it'll make sense with other advice

2022-08-23 17:53 UTC, noahmacaskill commented
Since allExtractors is private I verified that the output has null checksum values, let me know what you think.

https://github.com/QutEcoacoustics/emu/blob/8d4c4cadf29a82d780a3eaeaafc6255953b4e0c5/test/Emu.Tests/Commands/Metadata/MetadataCommandTests.cs#L86-L102

2022-08-23 17:55 UTC, noahmacaskill commented
Made this no longer readonly so I could filter out the HashCalculator when needed.

https://github.com/QutEcoacoustics/emu/blob/8d4c4cadf29a82d780a3eaeaafc6255953b4e0c5/src/Emu/Commands/Metadata/Metadata.cs#L28

Could also copy it to a new variable if that makes more sense?

2022-08-24 01:54 UTC, atruskie approved these changes
Looks good. You can keep `allExtractors` readonly with a small change. I'll do it.

2022-08-24 02:21 UTC, merged