CI Pipeline
QutEcoacoustics/emu pull request #98
Opened 2022-01-25 13:20 UTC by noahmacaskill

Draft PR for setting up CI pipeline. Tests are running, but some are failing.

2022-01-26 01:03 UTC, atruskie commented
Just a comment to begin with: you've based this branch off of commits that aren't in the main repo. Always update your forks before you start new work.

![image](https://user-images.githubusercontent.com/1452968/151085509-90f69481-301c-490e-9927-0e752b5048e4.png)

2022-01-26 01:15 UTC, atruskie requested changes

2022-01-26 01:15 UTC, atruskie commented on .github/workflows/dotnet.yml
> +    branches: [ master, CIpipeline ]
We should run tests on every branch, not just `master` and `CIpipeline`.  Try:

```yaml
on:
  push:
    branches:
      - "*"
```

2022-01-26 01:15 UTC, atruskie commented on .github/workflows/dotnet.yml
> +    branches: [ master ]
same comment as above

2022-01-26 01:15 UTC, atruskie commented on .github/workflows/dotnet.yml
> +        dotnet-version: 6.0.x
You can omit the version, and the version installed will be based off of the `global.json` file: https://github.com/actions/setup-dotnet#usage

2022-01-26 01:15 UTC, atruskie commented on .github/workflows/dotnet.yml
> +    runs-on: ubuntu-latest
It'd be good to see a matrix build here for windows, macos, and linux

2022-01-26 01:15 UTC, atruskie commented on test/MetadataUtility.Tests/TestHelpers/Extensions.cs
> +        public static string toCrLf(string str)
Methods have a leading capital in .NET

2022-01-26 01:16 UTC, atruskie commented
Ok, since the tests could keep failing for a while, I'd rather see the main repo start building on changes. 

So make the changes suggested above, then we'll merge, and deal with tests in another edit

2022-01-26 20:03 UTC, noahmacaskill commented
I think everything's been addressed. Moved some things around with some rebasing to clean those old commits out of this fork. Made a super basic matrix build for running on windows, macos and ubuntu, noticed AP had a lot more detail here, can bring some more of that over if needed. Since some of our tests are still failing, the pipeline was halting execution as soon as one failed, to alleviate this I threw in a "continue-on-error" flag so that they would all run.

Another interesting thing I noticed, every once and a while the tests crash before they've all been run (upon a rerun it will usually run all the way through though I haven't changed anything). Error message:

![Aborted tests](https://user-images.githubusercontent.com/64220701/151237887-73bbcf9a-e3de-4a0a-b13b-debbb53038c0.PNG)

Will see if I can figure this out. If there's any other feedback, let me know!

2022-01-26 21:41 UTC, noahmacaskill commented
Think I've solved the issue of the tests crashing, seems the issue was coming from [here](https://github.com/QutEcoacoustics/emu/blob/43354c0db8c77ced73be69316bf82243dd2a9efe/test/MetadataUtility.Tests/TestHelpers/FixtureHelper.cs#L109). For some reason this was sometimes trying to delete a temporary directory that doesn't exist (anymore at least). Though that seems to fix it, I'm not sure what was causing it to happen.

2022-01-26 23:47 UTC, atruskie commented
@noahmacaskill that's good information. `TestTempDir` is only used in one spot: https://github.com/QutEcoacoustics/emu/blob/8244ad941296ba3ad01f1fc60b370fa45d3dabf4/test/MetadataUtility.Tests/Utilities/FileMatcherTests.cs#L67

I think given the type of code involved here, we'll just add a try/catch around that directory deletion.

2022-01-26 23:49 UTC, atruskie commented
(Sorry - fat-thumbed it)

Okay time to merge. I'd like you to squash all your commits in this branch into one. Then I'll merge it.

https://stackoverflow.com/questions/43978823/how-to-squash-commits-in-one-branch

2022-01-26 23:49 UTC, atruskie commented
(Sorry - fat-thumbed it)

Okay time to merge. I'd like you to squash all your commits in this branch into one. Then I'll merge it.
https://stackoverflow.com/questions/43978823/how-to-squash-commits-in-one-branch

2022-01-27 16:10 UTC, noahmacaskill commented
Looks like the same error was being encountered [here](https://github.com/QutEcoacoustics/emu/blob/43354c0db8c77ced73be69316bf82243dd2a9efe/test/MetadataUtility.Tests/TestHelpers/TempFile.cs#L54-L65), followed the same logic for this try/catch.

2022-01-27 16:50 UTC, noahmacaskill commented
Squashed into one commit

2022-01-27 22:05 UTC, merged